---
title: "CaseStudy8"
author: "Mallory Dickerson"
date: "10/24/2022"
output: 
  html_document:
    keep_md: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lubridate)
library(downloader)
```
```{r}
business_data <- tempfile()
download("https://github.com/WJC-Data-Science/DTS350/raw/master/sales.csv", "business_data", mode = 'wb')
business_data <- read_csv("business_data")

```
creating the correct time aggregations
```{r}
revenue_data <- business_data %>%
  with_tz(tzone = "Us/Mountain") %>%
  mutate(hour = ceiling_date(Time, "hour"),
         day = ceiling_date(Time, "day"),
         week = ceiling_date(Time, "week"),
         month = ceiling_date(Time, "month"))

head(revenue_data)
        
```

Sales by month
```{r}
revenue_data %>%
  mutate(month = month(month)) %>%
  group_by(Name, month) %>%
  summarize(across(Amount,sum)) %>%
  ggplot(aes(x = month, y = Amount, color = Name)) +
  geom_point() +
  geom_line() +
  facet_wrap(~Name, scales = 'free') +
  labs(x = "Month",
       y = "Amount of Sales",
       title = "Company Sales by Month") +
  theme_bw()

              
```
company sales per week
```{r}
revenue_data %>%
  mutate(week = week(week)) %>%
  group_by(Name, week) %>%
  summarize(across(Amount,sum)) %>%
  ggplot(aes(x = week, y = Amount, color = Name)) +
  geom_point() +
  geom_line() +
  facet_wrap(~Name, scales = 'free') +
  labs(x = "Week",
       y = "Amount of Sales",
       title = "Company Sales by Week") +
  theme_bw()
```
company sales per day
```{r}
revenue_data %>%
  mutate(day = wday(day)) %>%
  group_by(Name, day) %>%
  summarize(across(Amount,sum)) %>%
  ggplot(aes(x = day, y = Amount, color = Name)) +
  geom_point() +
  geom_line() +
  facet_wrap(~Name, scales = 'free') +
  labs(x = "Day",
       y = "Amount of Sales",
       title = "Company Sales by Day") +
  theme_bw()
```

company sales by hour
```{r}
revenue_data %>%
  mutate(hour = hour(hour)) %>%
  group_by(Name, hour) %>%
  summarize(across(Amount,sum)) %>%
  ggplot(aes(x = hour, y = Amount, color = Name)) +
  geom_point() +
  geom_line() +
  facet_wrap(~Name, scales = 'free') +
  labs(x = "Hour",
       y = "Amount of Sales",
       title = "Company Sales by Hour") +
  scale_x_continuous(limits = c(0,24), breaks = seq(0,24,4)) +
  theme_bw()
```

```{r}
total_sales <- revenue_data %>%
  group_by(Name) %>%
  summarise(across(Amount, sum))
```

```{r}
total_sales %>%
  mutate(Name = as.factor(fct_reorder(Name, Amount))) %>%
  arrange(desc(Amount)) %>%
  ggplot(aes(x = Name, y = Amount, fill = Name)) +
    geom_col() +
    labs(x = 'Company', y = 'Total Sales', title = 'Total Sales by Company') +
    theme_bw() +
    theme(legend.position = 'none')
```

