---
title: "Task19"
author: "Mallory Dickerson"
date: "11/3/2022"
output: 
  html_document:
    keep_md: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggplot2)
library(maps)
library(ggrepel)
library(sf)
library(USAboundaries)
library(USAboundariesData)
```

```{r}
states <- sf::st_as_sf(map("state", plot = FALSE, fill = TRUE))

Idaho_counties <- us_counties(states = "ID")

UScities <- us_cities()

ggplot() +
  geom_sf(data = states, fill = NA) +
  geom_sf(data = Idaho_counties, fill = NA)
```
## getting biggest cities
```{r}
largest_cities <- UScities %>%
  filter(state_name != "Alaska", state_name != "Hawaii") %>%
  group_by(state_name) %>%
  arrange(desc(population)) %>%
  slice(1:3)

head(largest_cities)
```
## biggest city in each state
```{r}
largest <- largest_cities %>%
   slice(1:1)

largest
```
## middle city in each state
```{r}
middle <- largest_cities %>%
  slice(2:2)
```

## smaller city in each state
```{r}
smaller <- largest_cities %>%
  slice(3:3)
```


```{r}
ggplot() +
  geom_sf(data = states, fill = NA) +
  geom_sf(data = Idaho_counties, fill = NA) +
  geom_sf(data = largest, aes(size = population/1000), color = "darkblue") +
  geom_sf(data = middle, aes(size = population/1000), color = "blue") +
  geom_sf(data = smaller, aes(size = population/1000), color = "lightblue") +
  geom_sf_label(data = largest, aes(label = city), color = 'darkblue', size = 2, nudge_x = 1.5, nudge_y = .5) +
  scale_size_continuous("Population\n(1000)") +
  labs(x = " ",
       y = " ") +
  theme_bw()
```

